const doctorDomain = process.env.NEXT_PUBLIC_DOCTOR_URL;

export const ENDPOINTS = {
    login: '/login',
    signup: '/signup',
    user: '/user',
    updateProfile: '/update-profile',
    dashboard: '/dashboard',
    forgetPassword: '/forget-password',
    resendOtp: '/resend-otp',
    verifyOtp: '/verify-otp',
    getFamilyMember: '/family-member',
    deleteMember: '/family-member/',
    addFamilyMember: '/family-member',
    updateFamilyMember: '/family-member/',
    getReportsList: '/medical-record',
    deleteReport: '/medical-record/',
    deleteReportFile: '/medical-record/file/',
    addReport: '/medical-record',
    editReport: '/medical-record/update/',
    getDoctors: '/doctor/listing',
    shareReport: '/medical-record/share',
    shareReportRemove: '/medical-record/unshare/',
    artcleFeedback: '/review-article',
    InstantMedicalRecord: '/instant-medical-record',
    getInstantReportList: '/instant-medical-record',
    getAppointments: '/appointment?status=',
    deleteAppointment: '/appointment/cancel/',
    addAppointment: '/appointment',
    updateAppointment: '/appointment/',
    updateInstantRecord: '/instant-medical-record/update',
    deleteInstantReportFile: 'instant-medical-record/file/',
};

export const UrduURL = {
    dashboard: '/ur/dashboard',
    healthCheckHistory: '/ur/health-check-history',
    medicalRecordes: '/ur/medical-recordes',
    familyMembers: '/ur/family-members',
    updateProfile: '/ur/update-profile',
    bookAnAppointment: '/ur/book-an-appointment',
    medicalHistory: '/ur/medical-history',
    medicalSubscription: '/ur/subscriptions',
}

export const URL = {
    home: '/',
    login: '/phone-number',
    signup: '/signup',
    loginPhone: '/login/phone-number',
    otp: '/verify-otp',
    createProfile: '/create-profile',
    dashboard: '/dashboard',
    reviewAndBook: '/appointment/review-and-book',
    selectpaymentMethod: '/selectpaymentMethod',
    paymentConfimation: '/paymentConfimation',
    accountConfirmation: '/account-confirmation',
    healthCheckSubscription: '/health-check-subscription',
    startVitalScan: '/start-vital-scan',
    scanStarted: '/scan-started',
    addFamilyMember: '/edit-family-member',
    editFamilyMember: '/edit-family-member',
    updateProfile: '/update-profile',
    familyMembers: '/family-members',
    addFamilyMembers: '/add-family-members',
    // instantConsultant: '/instant-consultation',
    instantConsultant: '/doctor-now',
    uploadMedicalRecordes: '/upload-medical-recordes',
    medicalRecordes: '/medical-recordes',
    medicalHistory: '/medical-history',
    medicalSubscription: '/subscriptions',
    editMedicalRecords: '/medical-record/edit',
    newMedicalRecords: '/medical-record/new',
    deleteReportFile: '/medical-record/file/',
    // deleteInstantReportFile:'instant-medical-recotd/file/3',
    viewMedicalRecords: '/medical-record/',
    bookAnAppointment: '/book-an-appointment',
    bookAnAppointmentDetails: '/book-an-appointment-details',
    healthCheckReuslt: '/health-check-result',
    healthCheckHistory: '/health-check-history',
    sehatAtoZ: '/page/sehat-scan',
    healthCheck: '/sehatscan',
    findADoctor: '/find-a-doctor',
    subscriptionPage: '/subscription',
    termsCondintion: '/term-and-conditions',
    privacyPolicy: '/privacy-policy',
    aboutMeriSehat: '/about-meri-sehat',
    discoverWellness: '/discover-wellness',
    consultationStarted: '/consultation-started',
    videoScheduledAppointment: '/video-consultation',
    doctorListing: '/doctors/karachi',
    doctorDetail: '/doctor',
    searchDoctor: '/search-for-doctor',
    articleInnerPage: '/article-inner-page',
    discoverWellnessInner: '/discover-wellness-inner',
    viewAllSpecailist: '/find-a-doctor/view-all-specailist',
    doctorRegistration: doctorDomain
};
